package ar.edu.unju.fi.listas;

import java.util.ArrayList;
import java.util.List;

import org.springframework.stereotype.Component;

import ar.edu.unju.fi.entity.Producto;

/**
 * 
 * @author Farja Naima Blanca
 *
 */
@Component
public class ListaProductos {
	
	private List<Producto> productos;
	
	/**
	 * Constructor de la clase ListaProductos.
	 * Inicializa la lista de productos y agrega algunos productos de ejemplo.
	 */
	
	public ListaProductos() {
		productos = new ArrayList<Producto>();
		productos.add(new Producto("1110", "Pedigree Adulto", "Pedigree Adulto es un alimento especialmente formulado para perros adultos, diseñado para satisfacer sus necesidades nutricionales específicas. Contiene una mezcla equilibrada de proteínas, carbohidratos, vitaminas y minerales para promover la salud y el bienestar general de tu perro adulto. Este alimento se adapta a perros de diferentes razas y tamaños, brindándoles la nutrición adecuada para mantener un peso saludable y una energía óptima.", 12600.00 , 30, "Alimento perro adulto"));
        productos.add(new Producto("1111", "Raza Adulto","Raza Adulto es un alimento creado pensando en las necesidades nutricionales de perros adultos de diferentes razas. Reconoce que cada raza tiene características específicas y proporciona una combinación balanceada de ingredientes que se adaptan a esas necesidades. Este alimento está enriquecido con nutrientes clave para mantener la salud óptima de la piel, el pelaje, los huesos y las articulaciones, ayudando a mantener a tu perro adulto en excelente estado físico y promoviendo una vida activa.", 8000.00, 30 ,"Alimento perro adulto"));
        productos.add(new Producto("1112", "Sabrosito Adulto","Sabrosito Adulto es un alimento delicioso y nutritivo diseñado para perros adultos. Está hecho con ingredientes de alta calidad, incluyendo proteínas, carbohidratos, vitaminas y minerales esenciales para satisfacer las necesidades nutricionales de tu perro adulto. Además de ser sabroso, este alimento está formulado para promover una digestión saludable y un sistema inmunológico fuerte. Proporciona la energía y los nutrientes necesarios para mantener a tu perro adulto en una condición física óptima y ayudarle a mantenerse feliz y sano.", 9500.00, 20 ,"Alimento perro adulto"));
        productos.add(new Producto("1113", "Pedrigree cachorro","Pedigree Cachorro es un alimento especialmente formulado para perros cachorros, brindándoles la nutrición adecuada en esta etapa crucial de crecimiento y desarrollo. Contiene una mezcla equilibrada de proteínas, vitaminas, minerales y otros nutrientes esenciales para promover un desarrollo óptimo de los huesos, músculos y sistema inmunológico. Este alimento proporciona la energía necesaria para que los cachorros se mantengan activos y saludables, ayudándolos a convertirse en perros adultos fuertes y vitales.", 9600.00, 10 , "Alimento perro chachorro"));
        productos.add(new Producto("1114", "Raza cachorro","Raza Cachorro es un alimento especialmente formulado para satisfacer las necesidades nutricionales de los cachorros de diferentes razas. Reconociendo que cada raza tiene características únicas, este alimento proporciona una combinación balanceada de ingredientes que promueven el desarrollo adecuado de la raza específica. Está enriquecido con nutrientes esenciales para el crecimiento óptimo de los huesos, la salud de la piel y el pelaje, y el desarrollo de una musculatura fuerte. Ayuda a los cachorros a alcanzar todo su potencial genético y a prepararlos para una vida adulta saludable.", 6000.00, 10 ,"Alimento perro cachorro"));
        productos.add(new Producto("1115", "Sabrocito cachorro","Sabrosito Cachorro es un alimento delicioso y nutritivo diseñado específicamente para perros cachorros. Hecho con ingredientes de alta calidad, este alimento proporciona los nutrientes esenciales que los cachorros necesitan para un crecimiento y desarrollo saludables. Contiene una mezcla equilibrada de proteínas, grasas, carbohidratos, vitaminas y minerales para satisfacer las necesidades energéticas y nutricionales de los cachorros en crecimiento. Además de ser sabroso, este alimento también es fácil de digerir, lo que ayuda a promover una buena salud digestiva en los cachorros.", 7600.00, 10 , "Alimento perro cachorro"));
        productos.add(new Producto("1116", "Whiskas Adulto","Whiskas Gato Adulto es un alimento diseñado específicamente para satisfacer las necesidades nutricionales de los gatos adultos. Contiene una mezcla equilibrada de proteínas, vitaminas y minerales que promueven la salud y el bienestar general de tu gato. Este alimento está enriquecido con taurina, un nutriente esencial para la salud ocular y el funcionamiento adecuado del corazón. Además, ofrece una textura y sabor irresistibles que atraen a los gatos, asegurando que disfruten de cada comida." ,8000.00, 30 ,  "Alimento gato adulto"));
        productos.add(new Producto("1117", "Purina Cat Chow Adulto","Purina Cat Chow Gato Adulto es un alimento completo y equilibrado para gatos adultos. Está formulado con ingredientes de alta calidad para proporcionar los nutrientes esenciales que los gatos necesitan para mantener una buena salud. Este alimento contiene proteínas de alta calidad para apoyar la musculatura, así como vitaminas y minerales para fortalecer el sistema inmunológico y promover una piel saludable y un pelaje brillante. Con Purina Cat Chow, puedes estar seguro de que tu gato adulto está recibiendo una nutrición adecuada.", 4500.00, 20 ,  "Alimento gato adulto"));
        productos.add(new Producto("1118", "Raza gato adulto","Raza Gato Adulto es un alimento diseñado específicamente para satisfacer las necesidades nutricionales de los gatos adultos de diferentes razas. Reconociendo que cada raza tiene características únicas, este alimento proporciona una combinación balanceada de ingredientes que se adaptan a esas necesidades específicas. Está formulado con proteínas de alta calidad para mantener una masa muscular óptima, ácidos grasos esenciales para una piel sana y un pelaje brillante, y antioxidantes para apoyar el sistema inmunológico. Con este alimento, puedes ayudar a tu gato adulto a mantenerse en su mejor estado físico y promover una vida activa y saludable.", 9500.00, 30 ,  "Alimento gato adulto"));
        productos.add(new Producto("1119", "Whiskas gatito","Whiskas Gatito es un alimento especialmente formulado para satisfacer las necesidades nutricionales de los gatitos en crecimiento. Contiene una mezcla equilibrada de proteínas, vitaminas y minerales que apoyan un desarrollo saludable de los huesos, músculos y sistema inmunológico de los gatitos. Este alimento está enriquecido con taurina, un nutriente esencial para el crecimiento y desarrollo adecuados de los ojos y el corazón. Además, cuenta con una textura y sabor irresistibles que los gatitos adoran, garantizando que disfruten de cada bocado.", 6500.00, 10 , "Alimento gato cachorro"));
        productos.add(new Producto("1120", "Purina Cat Chow gatito","Purina Cat Chow Gatito es un alimento completo y equilibrado para gatitos en crecimiento. Está formulado con ingredientes de alta calidad para proporcionar los nutrientes esenciales que los gatitos necesitan en esta etapa crucial. Contiene proteínas de alta calidad para apoyar el desarrollo muscular, así como vitaminas y minerales para fortalecer el sistema inmunológico y promover una piel saludable y un pelaje brillante. Con Purina Cat Chow, puedes estar seguro de que estás brindando a tu gatito la nutrición adecuada para un crecimiento y desarrollo óptimos.", 8200.00, 10 , "Alimento gato cachorro"));
        productos.add(new Producto("1121", "Raza gatito","Raza Gatito es un alimento diseñado específicamente para satisfacer las necesidades nutricionales de los gatitos en crecimiento de diferentes razas. Reconociendo que cada raza tiene requerimientos únicos, este alimento proporciona una mezcla equilibrada de ingredientes adaptados a esas necesidades específicas. Está formulado con proteínas de alta calidad para el desarrollo muscular, ácidos grasos esenciales para una piel saludable y un pelaje brillante, y antioxidantes para apoyar un sistema inmunológico fuerte. Con este alimento, puedes ayudar a tu gatito a alcanzar su máximo potencial genético y asegurar un crecimiento saludable y equilibrado.", 6000.00, 10 , "Alimento gato cachorro"));
        productos.add(new Producto("1122", "Hueso","El juguete en forma de hueso es perfecto para satisfacer el instinto natural de masticación de tu mascota. Está diseñado con materiales duraderos y resistentes, ideales para perros de todas las razas y tamaños. El hueso brinda horas de diversión y entretenimiento, ayudando a fortalecer los dientes y las encías de tu mascota. Además, su forma ergonómica facilita el agarre y la manipulación, promoviendo el ejercicio físico y mental.",900.00, 0 , "Juguete"));
        productos.add(new Producto("1123", "Soga","El juguete de soga es un clásico favorito de perros de todas las edades. Fabricado con hilos resistentes y duraderos, este juguete ofrece múltiples usos. Puedes usarlo para jugar a juegos de tira y afloja con tu mascota, fortaleciendo los músculos y fomentando el vínculo entre ustedes. También es ideal para juegos interactivos de búsqueda y recuperación. La textura de la soga ayuda a mantener los dientes limpios y saludables al tiempo que satisface el instinto natural de masticación.", 1200.00, 10,  "Juguete"));
        productos.add(new Producto("1124", "Sapito","es una opción divertida y estimulante para gatos y perros pequeños. Su diseño colorido y textura suave llamará la atención de tu mascota y despertará su curiosidad. El sapito suele tener un relleno suave y puede emitir sonidos cuando se aprieta, lo que añade emoción y entretenimiento durante el juego. Este juguete es perfecto para actividades de caza y juego interactivo, ayudando a mantener a tu mascota activa y entretenida.", 1200.00, 20,  "Juguete"));
        productos.add(new Producto("1125", "Collar Star Wars"," ¡Que la fuerza esté con tu perro mientras camina con estilo! Este collar inspirado en Star Wars es perfecto para los fans de la saga galáctica y sus fieles compañeros caninos. Confeccionado con materiales duraderos y de alta calidad, este collar presenta un diseño único que presenta icónicos personajes y símbolos de Star Wars. Además de lucir genial, el collar proporciona comodidad y seguridad con su ajuste ajustable y cierre resistente. ¡Tu perro se convertirá en el Jedi más elegante de la galaxia con este collar de Star Wars!", 1800.00, 50, "Accesorios"));
        productos.add(new Producto("1126", "Laser","El juguete láser es la manera perfecta de estimular el instinto de caza de tu gato de forma divertida y segura! Con solo presionar un botón, un rayo láser se proyecta en diferentes direcciones, creando movimientos impredecibles que mantendrán a tu gato persiguiéndolo emocionado. Este juguete ayuda a mantener a tu gato activo, ágil y mentalmente estimulado. ¡Observa cómo tu felino se sumerge en un frenesí de caza mientras persigue el rayo láser por toda la habitación.", 600.00, 0, "Juguete"));
        productos.add(new Producto("1127", "Varilla para gato","es una herramienta irresistible para jugar con tu gato. Diseñado para imitar a las presas naturales, este juguete cuenta con una varilla liviana y un cordón que sostiene plumas suaves y coloridas en el extremo. Al mover la varilla y agitar las plumas, podrás provocar el instinto cazador de tu gato y estimular su agilidad. Este juguete permite una interacción activa y divertida entre tú y tu gato, fomentando el vínculo y brindando horas de entretenimiento.", 800.00, 10, "Juguete"));
        productos.add(new Producto("1128", "Ratoncito","es un clásico que atrae a los gatos de todas las edades. Este juguete adorable presenta un diseño realista de un ratón, con colores y texturas que capturan la atención de tu gato. Ya sea de felpa, plástico o tela, el ratoncito es suave al tacto y tiene un tamaño perfecto para que tu gato lo persiga, lo atrape y lo arañe. Este juguete despierta el instinto de caza de tu gato y le brinda una experiencia de juego satisfactoria y divertida. ¡Observa cómo tu gato muestra su agilidad y destreza mientras se divierte con su ratoncito favorito.", 1200.00, 20, "Juguete"));
        productos.add(new Producto("1129", "Collar Batman","Tu gato se convertirá en el héroe más intrépido de la noche con este collar inspirado en Batman. Diseñado pensando en los fans del Caballero Oscuro, este collar presenta el icónico logotipo de Batman en su diseño. Fabricado con materiales suaves y cómodos, el collar es ligero para adaptarse al estilo de vida activo de tu gato. También cuenta con un cierre seguro y ajustable para garantizar un ajuste perfecto. Con este collar de Batman, tu gato estará listo para enfrentar aventuras y proteger la ciudad felina con su propio estilo único y heroico.", 1800.00, 50, "Accesorios"));
		

		
	}
	
	/**
	 * Obtiene la lista de productos.
	 * @return la lista de productos
	 */

	public List<Producto> getProductos() {
		return productos;
	}

	public void setProductos(List<Producto> productos) {
		this.productos = productos;
	}
	
}
